### ISSUE TITLE
status_data.hpp Battery information data types

### ISSUE THREAD

**Issue by TobyUllrich** [RoverRobotics/librover#15]
I'm a little confused by the data types used for the battery information in the status_data.hpp
```
bool battery1_SOC;
bool battery2_SOC;
```
Shouldn't the Battery_SOC (State of Charge) be an integer or float as it should go from 0% to 100%?

Second, there is the battery current.
```
unsigned short int battery1_current;
unsigned short int battery2_current;
```
During charging the current should be positive and during discharging negative. Is this a limitation of the hardware, that it can only send the absolute current of the battery and not the directionality?

**Comment by drhieu** [comment]
You are correct on the battery SOC. That is a missed label variable. It should be battery charger state for when it is plugged in or not. 
The variable went meant for the second option since it wouldn't work on any other robots, but you can still have the first option by moving the variable to the correct spot [here](https://github.com/RoverRobotics/librover/blob/214183f083c7363ed706efbde5a47c8db7a9ef23/src/protocol_pro.cpp#L222). 

For your second question.
Yes this is a limitation on the battery we are using.
