### ISSUE TITLE
Runtime error with Rover Pro "errorterminate called after throwing an instance of 'int' " 

### ISSUE THREAD

**Issue by ljnap** [RoverRobotics/librover#23]
Hi 
I am trying to setup Rover Pro drivers in my own computer and followed the instructions as per the Computer setup guide 3.1.0(latest). I am using Ubuntu 18.04 and ROS melodic. The Build was successful and status is shown as "Active(running)", but it is throwing an error "errorterminate called after throwing an instance of 'int' " followed by "[roverrobotics_driver-2] Process has died".

Could you please help me here to figure out what is going wrong or if I am missing anything?

**Comment by RoverRoboticsProduction** [comment]
Apologies for the delay in getting back to you. "errorterminate..." typically means that the payload computer is not seeing the robot. That is often because some connection has come unplugged. It could also be due to using an old Pro interface board with our new Pro installation. If you still need assistance with this please [contact us here](https://roverrobotics.com/pages/contact)

**Comment by eliasgoldsztejn95** [comment]
Hi,

We are having the same issue, also with Ubuntu 18.04 and ROS melodic. @ljnap, @RoverRoboticsProduction  could you tell us how you fixed it? Thanks
